package eu.tjago.biplookup;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Tomasz' at '13.01.16 20:21' with Gradle 2.7
 *
 * @author Tomasz, @date 13.01.16 20:21
 */
@SpringBootApplication
public class App {
    public static void main(String[] args) {

        SpringApplication.run(App.class, args);
    }
}
