/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Tomasz' at '13.01.16 20:21' with Gradle 2.7
 *
 * @author Tomasz, @date 13.01.16 20:21
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
